"""create cdn control plane schema

Revision ID: 2c3af01d0235
Revises:
Create Date: 2026-09-19 17:36:38.741072

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2c3af01d0235"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("origin_path", sa.String(length=512), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("cache_ttl_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "published", "archived", name="asset_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cache_ttl_seconds >= 0", name=op.f("ck_assets_cache_ttl_seconds_non_negative")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_assets_size_bytes_non_negative")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_assets_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("origin_path", name=op.f("uq_assets_origin_path")),
    )
    op.create_index(op.f("ix_assets_status"), "assets", ["status"], unique=False)
    op.create_table(
        "regions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("continent", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
    )
    op.create_index(op.f("ix_regions_code"), "regions", ["code"], unique=True)
    op.create_index(op.f("ix_regions_continent"), "regions", ["continent"], unique=False)
    op.create_table(
        "distribution_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_distribution_rules_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_distribution_rules_region_id_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_distribution_rules")),
        sa.UniqueConstraint("asset_id", "region_id", name="asset_id_region_id"),
    )
    op.create_table(
        "edge_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("public_ipv4", postgresql.INET(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("capacity_mbps", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "provisioning", "healthy", "degraded", "draining", "offline", name="node_status"
            ),
            nullable=False,
        ),
        sa.Column("agent_version", sa.String(length=32), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_load_percent", sa.SmallInteger(), nullable=False),
        sa.Column("active_connections", sa.Integer(), nullable=False),
        sa.Column("cache_hit_ratio", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "active_connections >= 0", name=op.f("ck_edge_nodes_active_connections_non_negative")
        ),
        sa.CheckConstraint("capacity_mbps > 0", name=op.f("ck_edge_nodes_capacity_mbps_positive")),
        sa.CheckConstraint(
            "current_load_percent >= 0 AND current_load_percent <= 100",
            name=op.f("ck_edge_nodes_current_load_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_edge_nodes_region_id_regions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edge_nodes")),
        sa.UniqueConstraint("hostname", name=op.f("uq_edge_nodes_hostname")),
    )
    op.create_index(
        "ix_edge_nodes_region_id_status", "edge_nodes", ["region_id", "status"], unique=False
    )
    op.create_index(
        "ix_edge_nodes_status_last_heartbeat_at",
        "edge_nodes",
        ["status", "last_heartbeat_at"],
        unique=False,
    )
    op.create_table(
        "purge_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "scope", sa.Enum("asset", "region", "global", name="purge_scope"), nullable=False
        ),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("path_pattern", sa.String(length=512), nullable=True),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "in_progress", "completed", "partially_failed", name="purge_status"),
            nullable=False,
        ),
        sa.Column("target_node_count", sa.Integer(), nullable=False),
        sa.Column("acknowledged_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(scope = 'asset' AND asset_id IS NOT NULL)"
            " OR (scope = 'region' AND region_id IS NOT NULL)"
            " OR (scope = 'global')",
            name=op.f("ck_purge_events_scope_target_present"),
        ),
        sa.CheckConstraint(
            "acknowledged_count >= 0 AND acknowledged_count <= target_node_count",
            name=op.f("ck_purge_events_acknowledged_count_within_target"),
        ),
        sa.CheckConstraint(
            "target_node_count >= 0", name=op.f("ck_purge_events_target_node_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_purge_events_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_purge_events_region_id_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purge_events")),
    )
    op.create_index(
        "ix_purge_events_status_created_at",
        "purge_events",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "asset_replicas",
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("pending", "cached", "stale", "purged", name="replica_state"),
            nullable=False,
        ),
        sa.Column("cached_version", sa.Integer(), nullable=True),
        sa.Column("bytes_cached", sa.BigInteger(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_replicas_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["edge_nodes.id"],
            name=op.f("fk_asset_replicas_node_id_edge_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("node_id", "asset_id", name=op.f("pk_asset_replicas")),
    )
    op.create_index(
        "ix_asset_replicas_asset_id_state", "asset_replicas", ["asset_id", "state"], unique=False
    )
    op.create_table(
        "node_heartbeats",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cpu_percent", sa.SmallInteger(), nullable=False),
        sa.Column("memory_percent", sa.SmallInteger(), nullable=False),
        sa.Column("bandwidth_out_mbps", sa.Integer(), nullable=False),
        sa.Column("active_connections", sa.Integer(), nullable=False),
        sa.Column("cache_hit_ratio", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.CheckConstraint(
            "active_connections >= 0",
            name=op.f("ck_node_heartbeats_active_connections_non_negative"),
        ),
        sa.CheckConstraint(
            "bandwidth_out_mbps >= 0",
            name=op.f("ck_node_heartbeats_bandwidth_out_mbps_non_negative"),
        ),
        sa.CheckConstraint(
            "cpu_percent >= 0 AND cpu_percent <= 100",
            name=op.f("ck_node_heartbeats_cpu_percent_range"),
        ),
        sa.CheckConstraint(
            "memory_percent >= 0 AND memory_percent <= 100",
            name=op.f("ck_node_heartbeats_memory_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["edge_nodes.id"],
            name=op.f("fk_node_heartbeats_node_id_edge_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_heartbeats")),
    )
    op.create_index(
        "ix_node_heartbeats_node_id_received_at",
        "node_heartbeats",
        ["node_id", sa.literal_column("received_at DESC")],
        unique=False,
    )
    op.create_table(
        "purge_acknowledgements",
        sa.Column("purge_event_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "result", sa.Enum("purged", "not_found", "failed", name="purge_result"), nullable=False
        ),
        sa.Column("detail", sa.String(length=255), nullable=True),
        sa.Column(
            "acknowledged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["edge_nodes.id"],
            name=op.f("fk_purge_acknowledgements_node_id_edge_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["purge_event_id"],
            ["purge_events.id"],
            name=op.f("fk_purge_acknowledgements_purge_event_id_purge_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "purge_event_id", "node_id", name=op.f("pk_purge_acknowledgements")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purge_acknowledgements")
    op.drop_index("ix_node_heartbeats_node_id_received_at", table_name="node_heartbeats")
    op.drop_table("node_heartbeats")
    op.drop_index("ix_asset_replicas_asset_id_state", table_name="asset_replicas")
    op.drop_table("asset_replicas")
    op.drop_index("ix_purge_events_status_created_at", table_name="purge_events")
    op.drop_table("purge_events")
    op.drop_index("ix_edge_nodes_status_last_heartbeat_at", table_name="edge_nodes")
    op.drop_index("ix_edge_nodes_region_id_status", table_name="edge_nodes")
    op.drop_table("edge_nodes")
    op.drop_table("distribution_rules")
    op.drop_index(op.f("ix_regions_continent"), table_name="regions")
    op.drop_index(op.f("ix_regions_code"), table_name="regions")
    op.drop_table("regions")
    op.drop_index(op.f("ix_assets_status"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###

    # Autogenerate creates the native enum types alongside the tables but does not
    # drop them: DROP TABLE leaves the type behind, so a downgrade followed by an
    # upgrade would fail with "type already exists".
    for enum_name in (
        "asset_status",
        "node_status",
        "purge_result",
        "purge_scope",
        "purge_status",
        "replica_state",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
